# stage 1
FROM node:latest as build-step
RUN mkdir -p /app
WORKDIR /app
COPY package.json /app
RUN npm install --save --legacy-peer-deps --force
COPY . /app
RUN npm run build

# stage 2
FROM nginx:latest
COPY nginx.config /etc/nginx/conf.d/default.conf
COPY --from=build-step /app/dist/angular-ecommerce /usr/share/nginx/html
EXPOSE 80

#docker build -f Dockerfile.yaml -t murugesh1996/mmv2-angular-ecommerce .
#docker run -d -it -p 4200:80/tcp --name angular-ecommerce murugesh1996/angular-ecommerce
#docker run -p 4200:80 murugesh1996/angular-ecommerce

#http://murugesh1996-ecommerce-lb-1526980251.ap-south-1.elb.amazonaws.com/


#https://www.youtube.com/watch?v=lEg8CbdvOLE